//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL
    {
        public int Registro_Veterinario { get; set; }
        public string IdAnimal { get; set; }
        public string Tipo_Animal { get; set; }
        public string Nombre_Animal { get; set; }
        public string Raza_Animal { get; set; }
        public Nullable<int> Edad_Animal { get; set; }
        public string Nombre_Dueño { get; set; }
    }
}
