//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auxiliar
    {
        public int Registro_Veterinario { get; set; }
        public string IdAuxiliar { get; set; }
        public string Registro { get; set; }
        public string Cita { get; set; }
        public string Dueño { get; set; }
        public string Animal { get; set; }
    }
}
