//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dueño
    {
        public int Registro_Veterinario { get; set; }
        public string IdDueño { get; set; }
        public string Nombre_Dueño { get; set; }
        public Nullable<int> Numero_Dui { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Email { get; set; }
        public Nullable<int> Numero_Telefono { get; set; }
    }
}
