//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Registro_Veterinario { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public Nullable<int> Indentificacion { get; set; }
        public string Veterinario { get; set; }
        public string Auxiliar { get; set; }
    }
}
