//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Veterinaria_SistemaEntities : DbContext
    {
        public Veterinaria_SistemaEntities()
            : base("name=Veterinaria_SistemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANIMAL> ANIMAL { get; set; }
        public virtual DbSet<Auxiliar> Auxiliar { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Diagnostico> Diagnostico { get; set; }
        public virtual DbSet<Dueño> Dueño { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Registro_Personal> Registro_Personal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
